# Generated by Django 6.0.4 on 2026-08-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["name"],
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assigned_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atribuído a",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Empresa"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="País"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cargo"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Código Postal"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="surname",
            field=models.CharField(max_length=100, verbose_name="Sobrenome"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
