# Generated by Django 6.0.4 on 2026-08-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_alter_contact_options_alter_contact_address_and_more"),
        ("interations", "0002_interaction_delete_interation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interaction",
            options={"verbose_name": "Interação", "verbose_name_plural": "Interações"},
        ),
        migrations.AlterField(
            model_name="interaction",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contacts.contact",
                verbose_name="Contato",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interaction",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="date_time",
            field=models.DateTimeField(verbose_name="Data e Hora"),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="type_interaction",
            field=models.CharField(
                choices=[
                    ("C", "Ligação"),
                    ("E", "E-mail"),
                    ("M", "Reunião"),
                    ("O", "Reunião"),
                ],
                max_length=50,
                verbose_name="Tipo de Interação",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
