# Generated by Django 6.0.4 on 2026-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_task_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("DONE", "DONE"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
