# Generated by Django 6.0.4 on 2026-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acconts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
