# Generated by Django 6.0.4 on 2026-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0002_alter_oppurtunity_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oppurtunity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
