# Generated by Django 6.0.4 on 2026-07-29 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_updated_at"),
        ("opportunities", "0003_alter_oppurtunity_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor Estimado"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PROSPECTING", "Prospecção"),
                            ("QUALIFICATION", "Qualificação"),
                            ("PROPOSAL", "Proposta"),
                            ("NEGOTIATION", "Negociação"),
                            ("CLOSED_WON", "Fechada Ganha"),
                            ("CLOSED_LOST", "Fechada Perdida"),
                        ],
                        default="PROSPECTING",
                        max_length=50,
                        verbose_name="Estágio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atribuído a",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="contacts.contact",
                        verbose_name="Contato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidade",
                "verbose_name_plural": "Oportunidades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Oppurtunity",
        ),
    ]
