# Generated by Django 6.0.4 on 2026-07-09 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clientes",
            new_name="Cliente",
        ),
    ]
