# Generated by Django 6.0.4 on 2026-07-13 09:20

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_remove_cliente_nome_completo_cliente_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="updated_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
