# Generated by Django 6.0.4 on 2026-07-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0004_alter_cliente_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
